[build]
	command = "eleventy"
	publish = "_site"

[[redirects]]
	from = "https://www.disquisitioner.com/posts/post_rsvp_iws2020/*"
	to = "https://www.disquisitioner.com/posts/2020/post-rsvp-iws2020/"
	status = 410
	force = true
